### ISSUE TITLE
[TRACKING] AWS Distribution for Kubeflow v1.6

### ISSUE THREAD

**Issue by surajkota** [awslabs/kubeflow-manifests#309]
AWS is testing Kubeflow on EKS as part of distribution testing. https://github.com/kubeflow/manifests/issues/2221

AWS need to verify the following features:
- [x] Vanilla Kubeflow
- [x] Load balancer integration
- [x] Cognito Integration
- [x] RDS integration for pipelines
- [x] RDS integration for Katib
- [x] S3 integration for pipelines
- [x] DLC in Jupyter Notebooks
- [x] EFS
- [x] FSx
- [x] AWS IAM Profile plugin
- [x] KServe
- [x] Cloudwatch
- [x] Update e2e tests
  - [x] #124 
- [x] #121 
- [x] #299 
- [x] #117 
- [x] #128 
- [x] #207 
- [x] #257 
- [x] #267 
- [x] Documentation updates to website
