### ISSUE TITLE
[TRACKING] AWS Distribution for Kubeflow v1.7

### ISSUE THREAD

**Issue by ryansteakley** [awslabs/kubeflow-manifests#576]
AWS is testing Kubeflow on EKS as part of distribution testing.

AWS need to verify the following features:

- [x] Vanilla Kubeflow
- [x] Load balancer integration
- [x] Cognito Integration
- [x]  RDS integration for pipelines
- [x] RDS integration for Katib
- [x] S3 integration for pipelines
- [x]  DLC in Jupyter Notebooks
- [x]  EFS
- [x]  FSx
- [x]  AWS IAM Profile plugin
- [x]  KServe
- [x]  Cloudwatch
- [x] Tensorboard using S3 as remote source
- [x]  Update e2e tests
- [x]  Documentation updates to website

**Comment by AlexandreBrown** [comment]
Should the list also include the testing of Tensorboard using S3 as remote source since it just got added or will be added to Kubeflow 1.7 RC?

**Comment by ryansteakley** [comment]
@AlexandreBrown Have added and tested it :)

**Comment by techwithshadab** [comment]
I can get `e2e tests updated`, Which branch we are working on for this?

**Comment by AlexandreBrown** [comment]
This issue should be fix before releasing v1.7 : https://github.com/awslabs/kubeflow-manifests/issues/609

**Comment by AlexandreBrown** [comment]
@surajkota @ryansteakley I suppose this can be closed since 1.7 was released?

**Comment by surajkota** [comment]
1.7 has been released
