### ISSUE TITLE
Create a FAQ page

### ISSUE THREAD

**Issue by surajkota** [awslabs/kubeflow-manifests#753]
<!- Please submit only documentation-related issues or requests for new documentation with this form.-->

Creating this issue to collect candidates for FAQ page and improving troubleshooting page

**What is the URL of the document?**
https://awslabs.github.io/kubeflow-manifests/docs/faq/

**FAQ**

- [ ] CA or Karpenter is not installed by default, customer can choose their preferred autoscaling option https://kubeflow.slack.com/archives/CKBA5D0MU/p1684521005817199
- [ ] How to integrate with external idp such as Okta, AzureAD etc.
- [ ] how to turn on automatic profile creation - https://github.com/awslabs/kubeflow-manifests/issues/529#issuecomment-1355593958
- [ ] CPU and memory limits https://github.com/awslabs/kubeflow-manifests/issues/540#issuecomment-1542836337
- [ ] How to add custom notebook images by default or update existing
- [ ] Group support in Profiles https://github.com/kubeflow/kubeflow/issues/7085, https://kubeflow.slack.com/archives/CKBA5D0MU/p1681157851604979
- [ ] Improve docs on KFP programmatic access https://github.com/awslabs/kubeflow-manifests/issues/493#issuecomment-1491046392, https://github.com/awslabs/kubeflow-manifests/issues/493#issuecomment-1542716612
- [ ] Exact steps for Notebook incluster auth to pipelines or improve OSS docs
- [ ] Existing solutions for profile creation https://github.com/awslabs/kubeflow-manifests/issues/492

**Troubleshooting**
- [ ] Node provisioning in Karpenter does not come with enough root volume storage https://github.com/awslabs/kubeflow-manifests/issues/748
- [ ] `oidc-authservice` pod does not come up because EBS CSI driver is not installed. [Instead of note, add the exact steps](https://awslabs.github.io/kubeflow-manifests/docs/deployment/create-eks-cluster/#create-eks-cluster-using-eksctl)
- [ ] Artifact URLs show minio prefix even with S3 deployment https://kubeflow.slack.com/archives/CKBA5D0MU/p1685659169416429?thread_ts=1685480252.095319&cid=CKBA5D0MU
- [ ] incorrect region picked up by pipeline https://github.com/awslabs/kubeflow-manifests/issues/729, https://kubeflow.slack.com/archives/CKBA5D0MU/p1683247067463769

```
Failed to get object in bucket BUCKET_NAME at path artifacts/train-until-good-pipeline-c2s7l/2023/05/04/train-until-good-pipeline-c2s7l-2854567371/main.log: S3Error: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-east-2'
```
- [ ] Problem if credentials are rotated with S3 IAM user deployment https://kubeflow.slack.com/archives/CKBA5D0MU/p1682016631463589
