### ISSUE TITLE
[TRACKING] AWS Distribution for Kubeflow v1.5

### ISSUE THREAD

**Issue by surajkota** [awslabs/kubeflow-manifests#91]
On 02/15 Kubeflow community meeting, manifests WG announced

Feature list:
- [ ] Vanilla Kubeflow
- [ ] Cognito Integration
- [ ] RDS integration for pipelines
- [ ] RDS integration for Katib
- [ ] S3 integration for pipelines
- [ ] DLC in Jupyter Notebooks
- [ ] https://github.com/awslabs/kubeflow-manifests/issues/76
- [ ] Secrets manager integration for credentials
- [ ] EFS
- [ ] FSx
- [ ] e2e tests
- [ ] Documentation updates to website

**Comment by surajkota** [comment]
Links to the recommended samples from manifests WG to run for testing: (ref: 2022-02-15 8:00AM community meeting notes)

> Distribution Testing Examples 
> - Notebook that helps validate environment (Notebook, training, tuning, serving)
> - E2E MNIST Notebook [example](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/kubeflow-pipelines/kubeflow-e2e-mnist.ipynb)
> - It’s also autoated as python/bash in https://github.com/kubeflow/manifests/tree/master/tests/e2e

**Comment by js-ts** [comment]
@surajkota are you going to make KServe default ?

**Comment by surajkota** [comment]
We will follow same as Kubeflow release

**Comment by akartsky** [comment]
Manually tested that current mainline works with EKS 1.20 
also successfully ran the https://github.com/kubeflow/manifests/tree/master/tests/e2e

**Comment by js-ts** [comment]
@akartsky as the upstream test exaple for https://github.com/kubeflow/manifests/tree/master/tests/e2e which is https://github.com/kubeflow/pipelines/blob/master/samples/contrib/kubeflow-e2e-mnist/kubeflow-e2e-mnist.ipynb
is updated you should try it out using that example as it uses kserve instead of kfserving .

**Comment by surajkota** [comment]
Great!! lets expand the matrix to test EKS - 1.19, 1.20 & 1.21 (same as 1.3,1.4) and run the mnist-e2e test from this PR: https://github.com/kubeflow/manifests/pull/2164 (this includes kserve) or the notebook Vedant has linked above

Nice to have is rds & s3 tested. It is fine to test this on just one version

1.21 is less risk since other distributions have tested it but I have not seen any update on 1.19 from any other distributions. We can take the call about supporting 1.19 or not later if its not working since it is too late to call out issues. Release tag is planned to be cut tomorrow as per schedule

**Comment by akartsky** [comment]
Tested EKS - 1.19, 1.20 & 1.21 and ran mnist-e2e test from the PR

**Comment by surajkota** [comment]
@akartsky please update on the community's issue as well

**Comment by akartsky** [comment]
> from this PR: [kubeflow/manifests#2164](https://github.com/kubeflow/manifests/pull/2164)

Done

**Comment by akartsky** [comment]
Found an [issue](https://github.com/kubeflow/manifests/issues/2165) with cache-deployer Pod

**Comment by Harikantipudi** [comment]
> @surajkota are you going to make KServe default ?

yes KServe comes with 1.5 by default

**Comment by ohke** [comment]
Hi.

As of June 2022, EKS supports k8s 1.22.
Will the Kubeflow v1.5 manifest support 1.22?

**Comment by surajkota** [comment]
Hi @ohke, Kubeflow 1.5 does not support K8s-1.22. This feature is under development and you can track it here: https://github.com/kubeflow/kubeflow/issues/6353. We expect K8s-1.22 to be supported in Kubeflow-1.6 and we will also 
 support for it as soon as Kubeflow is compatible.
